server:
  port: 8081
  servlet:
    context-path: /

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/hackathon2019?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver


