server:
  port: 8081
  servlet:
    context-path: /

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://remotemysql.com:3306/g1fG2FcAud?useSSL=false
    username: g1fG2FcAud
    password: MC3C5sgjcK
    driver-class-name: com.mysql.cj.jdbc.Driver


